config/routes.rb
Rails.application.routes.draw do
  resources :locations
  get 'home/index'

  root 'home#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @location = Location.new
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to action: "index", notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :description, :lat, :lng)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/home/_form.html.erb
<%= form_for(@location, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Nombre', :class=>"col-sm-4 control-label" %>
    <div class="col-sm-8">
    <%= f.text_field :name, :class=>"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label 'Latitud', :class=>"col-sm-4 control-label" %>
    <div class="col-sm-8">
    <%= f.text_field :lat, :class=>"form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label 'Longitud', :class=>"col-sm-4 control-label" %>
    <div class="col-sm-8">
    <%= f.text_field :lng, :class=>"form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label 'Descripción', :class=>"col-sm-4 control-label" %>
    <div class="col-sm-8">
    <%= f.text_area :description, :class=>"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-8">
    <%= f.button "Agregar Ubicación", class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="col-md-4">
  <!-- <form class="form-horizontal" action="" method="post">
    <div class="form-group">
      <label for="name" class="col-sm-4 control-label">Nombre</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="name" name="name" placeholder="">
      </div>
    </div>
    <div class="form-group">
      <label for="lng" class="col-sm-4 control-label">Latitud</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="lat" name="lat" disabled>
      </div>
    </div>
    <div class="form-group">
      <label for="lng" class="col-sm-4 control-label">Longitud</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="lng" name="lng" disabled>
      </div>
    </div>
    <div class="form-group">
      <label for="description" class="col-sm-4 control-label">Descripción</label>
      <div class="col-sm-8">
        <textarea name="description" id="description" class="form-control" rows="8" cols="20"></textarea>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-8">
        <button type="submit" class="btn btn-primary btn-block">Sign in</button>
      </div>
    </div>
  </form> -->
  <%= render 'form' %>
</div>
<div class="col-md-8">
  <div id="map">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Locations" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>


  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Locations API</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Ubicaciones", "/locations"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->
  <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class="col-md-12">
<p id="notice"><%= notice %></p>

<h1>Ubicaciones Registradas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.description %></td>
        <td><%= location.lat %></td>
        <td><%= location.lng %></td>
        <td><%= link_to 'Ver', location %></td>
        <td><%= link_to 'Editar', edit_location_path(location) %></td>
        <td><%= link_to 'Eliminar', location, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @location.description %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @location.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @location.lng %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>